version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: marina_adm
      POSTGRES_PASSWORD: mar123
      POSTGRES_DB: homework_13
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"

volumes:
  postgres_data:
